# Generated by Django 4.1.7 on 2023-03-25 21:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lectures", "0002_initial"),
        ("watchedlectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchedlecture",
            name="lastPlayed",
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="watchedlecture",
            unique_together={("user", "lecture", "lecture_num")},
        ),
    ]
