# Generated by Django 4.1.7 on 2023-03-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchedlectures", "0002_alter_watchedlecture_lastplayed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchedlecture",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
