# Generated by Django 4.1.7 on 2023-03-26 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watchedlectures", "0003_watchedlecture_is_completed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watchedlecture",
            name="duration",
        ),
    ]
